
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-embedded-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-embedded-app
  template:
    metadata:
      labels:
        app: hazelcast-embedded-app
    spec:
      containers:
      - name: springboot-app
        image: deepaannjohn/hazelcast-embedded-springboot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded-service
spec:
  selector:
    app: hazelcast-embedded-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
